# JupyterHub Helm Chart Values
fullnameOverride: "jupyterhub"

# Hub configuration
hub:
  nodeSelector:
    node: pve
  tolerations:
    - key: node-role
      operator: Equal
      value: backup
      effect: NoSchedule
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  
  config:
    JupyterHub:
      authenticator_class: dummy
    DummyAuthenticator:
      password: "ai-infra-password"
  
  db:
    pvc:
      storageClassName: "longhorn-ssd"
      accessModes:
        - ReadWriteOnce
      storage: 20Gi

# Proxy configuration
proxy:
  chp:
    nodeSelector:
      node: pve
    tolerations:
      - key: node-role
        operator: Equal
        value: backup
        effect: NoSchedule
  service:
    type: ClusterIP

# Ingress
ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - jupyter.local
  tls: []

# Single user server configuration
singleuser:
  nodeSelector:
    node: pve
  
  image:
    name: jupyter/tensorflow-notebook
    tag: latest
  
  cpu:
    limit: 2
    guarantee: 0.5
  memory:
    limit: 4G
    guarantee: 1G
  
  storage:
    type: dynamic
    dynamic:
      storageClass: "longhorn-ssd"
      pvcNameTemplate: "jupyter-{username}"
      volumeNameTemplate: "jupyter-{username}"
      storageAccessModes:
        - ReadWriteOnce
    capacity: 50Gi
  
  defaultUrl: "/lab"
  uid: 1000
  fsGid: 1000

# Scheduling configuration
scheduling:
  userScheduler:
    enabled: false
  
  podPriority:
    enabled: false

# Culling idle servers
cull:
  enabled: true
  timeout: 3600
  every: 600 