# MinIO Helm Chart Values
nameOverride: "minio"
fullnameOverride: "minio"

# Deployment mode
mode: standalone

# Node selection
nodeSelector:
  node: pve

# Tolerations for master node
tolerations:
  - key: node-role
    operator: Equal
    value: backup
    effect: NoSchedule

# Resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# Persistence
persistence:
  enabled: true
  storageClass: "longhorn-ssd"
  size: 200Gi
  accessModes:
    - ReadWriteOnce

# Service configuration
service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

# Ingress for Console
consoleIngress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - minio.local
  tls: []

# Ingress for API
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - minio-api.local
  tls: []

# Auth
auth:
  rootUser: admin
  rootPassword: ai-infra-minio-password

# Security context
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000 