# Standalone Ollama Helm Chart Values
# Backup AI сервис (отдельно от встроенного в Open WebUI)
# МАКСИМАЛЬНАЯ МОЩНОСТЬ: 96GB RAM + 40 CPU cores

nameOverride: "ollama-standalone"
fullnameOverride: "ollama-standalone"

# Node selection
nodeSelector:
  node: pve

# Runtime class для GPU
runtimeClassName: nvidia

# Tolerations for master node
tolerations:
  - key: node-role
    operator: Equal
    value: backup
    effect: NoSchedule

# Resources для backup Ollama - МАКСИМУМ для GPU!
resources:
  requests:
    memory: "32Gi"     # норм для старта, минимум на q4 модели 70B
    cpu: "8000m"       # 8 ядер на старт, хватит для подготовки
  limits:
    memory: "160Gi"    # можно даже 180, у тебя 200 есть
    cpu: "60000m"      # все 60 ядер отдаем — пусть молотит

# Persistence для backup моделей - ОГРОМНЫЙ объем!
persistentVolume:
  enabled: true
  storageClass: "longhorn-ssd"
  size: 200Gi  # 200GB хватит для кучи моделей!
  accessModes:
    - ReadWriteOnce

# Service configuration (стандартный порт Ollama)
service:
  type: ClusterIP
  port: 11434

ingress:
  enabled: true

  # -- IngressClass that will be used to implement the Ingress (Kubernetes 1.18+)
  className: "nginx"

  # -- Additional annotations for the Ingress resource.
  annotations: { }
    # kubernetes.io/ingress.class: traefik
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"

  # The list of hostnames to be covered with this ingress record.
  hosts:
    - host: ollama.local
      paths:
        - path: /
          pathType: Prefix

  # --  The tls configuration for hostnames to be covered with this ingress record.
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
# Environment variables для МАКСИМАЛЬНОЙ производительности GPU!
extraEnv:
  - name: OLLAMA_ORIGINS
    value: "*"
  - name: OLLAMA_DEBUG
    value: "1"

# Health checks - увеличиваем таймауты для GPU инициализации
livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: 11434
  initialDelaySeconds: 300          # 5 минут на загрузку модели
  periodSeconds: 60
  timeoutSeconds: 30
  failureThreshold: 5

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: 11434
  initialDelaySeconds: 180          # 3 минуты на инициализацию
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 10
