# Open WebUI Helm Chart Values
nameOverride: "open-webui"
fullnameOverride: "open-webui"

# Namespace
namespace: ai-infra

# Node selection
nodeSelector:
  node: pve

# Tolerations for master node
tolerations:
  - key: node-role
    operator: Equal
    value: backup
    effect: NoSchedule

# Resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# Persistence
persistence:
  enabled: true
  storageClass: "longhorn-ssd"
  size: 20Gi
  accessModes:
    - ReadWriteOnce

# Service configuration
service:
  type: ClusterIP
  port: 8080

# Environment variables
env:
  OLLAMA_BASE_URL: "http://ollama.ai-infra.svc.cluster.local:11434"
  WEBUI_SECRET_KEY: "ai-infra-secret-key"
  WEBUI_AUTH: "false"

# Ingress (правильная структура для Open WebUI chart)
ingress:
  enabled: true
  class: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: "ai.local"
  tls: false

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Probes
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10 